## Assignment 9: Numpy


### Task 1: Creating Numpy Arrays

In [50]:
import numpy as np


In [51]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
array.shape

(10,)

In [53]:
array.dtype

dtype('int64')

In [54]:
twoDarray= np.array([[1,2,3],[4,5,6],[7,8,9]])
twoDarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
twoDarray.shape

(3, 3)

In [56]:
twoDarray.dtype

dtype('int64')

In [57]:
list=[10,20,30,40,50]
larray=np.array(list)
larray

array([10, 20, 30, 40, 50])

In [58]:
larray.shape

(5,)

In [59]:
larray.dtype

dtype('int64')

## Task 2: Important Mathematical formula 

In [60]:
A = np.array([10,20,30,40])
B = np.array([1,2,3,4])

In [61]:
A+B

array([11, 22, 33, 44])

In [62]:
A-B

array([ 9, 18, 27, 36])

In [63]:
A*B

array([ 10,  40,  90, 160])

In [64]:
A/B

array([10., 10., 10., 10.])

In [65]:
A**2

array([ 100,  400,  900, 1600])

## Task 3: Important Numpy Mathematical Functions

In [66]:
values = np.array([2,4,6,8,10])

In [67]:
np.sqrt(values)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766])

In [68]:
np.exp(values)

array([7.38905610e+00, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03,
       2.20264658e+04])

In [69]:
np.log(values)

array([0.69314718, 1.38629436, 1.79175947, 2.07944154, 2.30258509])

In [70]:
np.sum(values)

np.int64(30)

In [71]:
np.cumsum(values)

array([ 2,  6, 12, 20, 30])

## Task 4: Aggregation Operations

In [72]:
data = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

data

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [73]:
# Raw wise sum      
np.sum(data, axis=1)

array([ 60, 150, 240])

In [74]:
# Column Wise Sum
np.sum(data, axis=0)

array([120, 150, 180])

In [75]:
np.min(data)

np.int64(10)

In [76]:
np.max(data)

np.int64(90)

In [77]:
np.mean(data)

np.float64(50.0)

## Task 5: Statistical Operations (Core Focus)

In [78]:
marks = np.array([78,85,90,66,72,88,95,60])

In [79]:
np.mean(marks)

np.float64(79.25)

In [80]:
np.median(marks)

np.float64(81.5)

In [81]:
np.var(marks)

np.float64(134.1875)

In [82]:
np.std(marks)

np.float64(11.583932838203095)

In [83]:
np.min(marks)

np.int64(60)

In [84]:
np.max(marks)

np.int64(95)

In [89]:
range=np.max(marks)-np.min(marks)
range

np.int64(35)

## Task 6: Percentile and sorting

In [86]:
sorted_marks=np.sort(marks)

In [87]:
sorted_marks

array([60, 66, 72, 78, 85, 88, 90, 95])

In [90]:
np.percentile(sorted_marks, 25)

np.float64(70.5)

In [91]:
np.percentile(sorted_marks, 50)

np.float64(81.5)

In [92]:
np.percentile(sorted_marks, 75)

np.float64(88.5)

In [93]:
sorted_marks>np.mean(sorted_marks)

array([False, False, False, False,  True,  True,  True,  True])

In [96]:
sum(sorted_marks>np.mean(sorted_marks))

np.int64(4)

## Task 7: Mini Use Case: Sales Analysis

In [97]:
sales=np.array([1200,1500,900,2000,1800,1700,1600])

In [98]:
sales

array([1200, 1500,  900, 2000, 1800, 1700, 1600])

In [99]:
# Total weekly sales
sum(sales)

np.int64(10700)

In [100]:
# Avarage Daily Sales =
np.mean(sales)

np.float64(1528.5714285714287)

In [101]:
# Highest sales 
np.max(sales)

np.int64(2000)

In [103]:
# Lowest sales
np.mean(sales)

np.float64(1528.5714285714287)

In [104]:
# Standard Deviation of sales
np.std(sales)

np.float64(345.2298849598449)

In [ ]:
# true means at that day the sales is above the avarage
sales>np.mean(sales)

array([False, False, False,  True,  True,  True,  True])